server:
  port: 31001
  tomcat:
    basedir: /var/tmp
    background-processor-delay: 30
    port-header: X-Forwarded-Port
      protocol-header: X-Forwarded-Proto
      protocol-header-https-value: https
      redirect-context-root: true
      remote-ip-header: X-Forwarded-For
      uri-encoding: UTF-8
      accesslog:
        enabled: true
        buffered: true
        directory: ./log
        file-date-format: .yyyy-MM-dd
        pattern: '%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-Agent}i" %D ms'
        prefix: access_log
        rename-on-rotate: false
        request-attributes-enabled: false
        rotate: true
        suffix: .log
spring:
  application:
    name: xc-service-manage-cms
  resources:
    static-locations: classpath:*
  datasource:
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://localhost:3306/scenic?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
   username: root
   password: root



